# Create rook shared filesystem
- name: ROOK - Create Rook Shared Filesystem
  k8s:
    kubeconfig: "{{ kubeconfig_file_path | default(omit) }}"
    state: present
    definition: "{{ lookup('template', 'storages/file-system.yaml.j2') | from_yaml }}"
  register: ret
  until: |
    not ret.get('failed', false)
    or ret.get('status', 200) != 200
  retries: "{{ k8s_task_retries | default(3) }}"
  delay: "{{ k8s_task_delay | default(15) }}"
  loop: "{{ ceph_file_systems }}"
  loop_control:
    label: "{{ item | to_nice_yaml }}"
  tags: storage_creation
