# Mount on host
- name: ROOK - Mount on host - create PVC
  k8s:
    kubeconfig: "{{ kubeconfig_file_path | default(omit) }}"
    definition: "{{ lookup('template', 'ceph-mount-pvc.yaml.j2') | from_yaml }}"
  register: ret
  until: |
    not ret.get('failed', false)
    or ret.get('status', 200) != 200
  retries: "{{ k8s_task_retries | default(3) }}"
  delay: "{{ k8s_task_delay | default(15) }}"
  loop: "{{ rook_mount_on_host }}"
  loop_control:
    label: "\n{{ item | to_nice_yaml }}"
  when: item.enabled | default(false)
  ignore_errors: yes
  tags:
  - storage_mount

- name: ROOK - Mount on host
  k8s:
    kubeconfig: "{{ kubeconfig_file_path | default(omit) }}"
    force: yes
    definition: "{{ lookup('template', 'ceph-mount.yaml.j2') | from_yaml }}"
  register: ret
  until: |
    not ret.get('failed', false)
    or ret.get('status', 200) != 200
  retries: "{{ k8s_task_retries | default(3) }}"
  delay: "{{ k8s_task_delay | default(15) }}"
  loop: "{{ rook_mount_on_host }}"
  loop_control:
    label: "\n{{ item | to_nice_yaml }}"
  when: item.enabled | default(false)
  tags:
  - storage_mount
